insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (1, 'Sibeal Rance', 19, 'Tigbinan', '1996-03-28', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (2, 'Christine Asch', 20, 'Halmstad', '1996-03-16', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (3, 'Curt Setch', 20, 'Atolina', '1999-04-15', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (4, 'Flin Gaunson', 21, 'Makuyuni', '1998-12-30', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (5, 'Ximenez Sidebotham', 19, 'Tambovka', '2000-03-11', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (6, 'Cordie Almak', 21, 'Arroyo Salado', '1997-02-17', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (7, 'Bil Larkcum', 19, 'Khantaghy', '1997-09-10', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (8, 'Markos Zannotti', 21, 'Tuen Mun', '2000-09-25', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (9, 'Rossie Dykas', 20, 'Yasenevo', '1998-11-07', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (10, 'Dorine Stoddard', 21, 'Karnobat', '1999-06-14', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (11, 'Ferdie Kubecka', 19, 'Kupu', '1996-11-17', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (12, 'Andros Allsobrook', 19, 'Vantaa', '2000-04-02', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (13, 'Bartholomeo Tumulty', 21, 'Sacramento', '1998-06-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (14, 'Pincas Boutton', 19, 'Virginia Beach', '1996-03-08', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (15, 'Aaron Szimon', 19, 'Pescadería', '1998-08-16', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (16, 'Tabbi Drinnan', 20, 'Mó', '2000-08-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (17, 'Stu Samarth', 21, 'Qujing', '2000-01-03', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (18, 'Bili Spaxman', 19, 'Campo de la Cruz', '2000-08-07', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (19, 'Elisabet Sessuns', 20, 'Cisompet', '2000-02-10', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (20, 'Viv Newbury', 21, 'Poá', '1996-01-29', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (21, 'Alix Ridge', 20, 'Chợ Gạo', '1997-08-25', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (22, 'Lorelle Mc Grath', 21, 'Kowingir', '1997-02-11', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (23, 'Rice McKoy', 20, 'Pendembu', '1997-09-13', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (24, 'Codi Padula', 21, 'Guangyi', '1996-06-10', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (25, 'Bobbee Dinjes', 21, 'Jiaoshanhe', '1999-12-30', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (26, 'Matthew Smithers', 20, 'Kashirskoye', '1996-02-29', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (27, 'Janice Bowmen', 19, 'Brasília', '1997-08-27', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (28, 'Mercy Boolsen', 21, 'Qingxi', '1998-03-28', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (29, 'Claude Purcell', 21, 'Yujia', '1999-08-20', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (30, 'Ertha Sculley', 21, 'Wakduwa’ Barat', '1999-11-07', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (31, 'Randall Troke', 20, 'Tanjung', '1998-01-29', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (32, 'Becki Macrae', 19, 'Mingyuedian', '1998-06-25', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (33, 'Borden Burdett', 20, 'Bernay', '1999-02-18', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (34, 'Curr Hodgon', 20, 'Špišić-Bukovica', '1997-11-17', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (35, 'Abrahan Kuhnhardt', 20, 'Kusatsu', '2000-08-28', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (36, 'Ashley Spedding', 20, 'Fasi', '1998-10-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (37, 'Rossy Winspear', 19, 'Chamni', '1998-07-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (38, 'Kevyn Leason', 21, 'Bessonovka', '1997-04-28', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (39, 'Marijo Filippov', 19, 'Ailibugai', '2000-06-03', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (40, 'Kenyon Bott', 19, 'Oslo', '2000-08-13', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (41, 'Pascale Dear', 20, 'Alto do Estanqueiro', '1999-07-11', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (42, 'Rozalin Williamson', 19, 'Santyoku', '1999-08-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (43, 'Paulette Marchington', 21, 'Bacag', '2000-03-16', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (44, 'Haley Brayshaw', 20, 'Jokkmokk', '1999-02-21', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (45, 'Poul Scirman', 19, 'Santa Marta de Penaguião', '1998-03-22', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (46, 'Gavan Wheelhouse', 21, 'Xiaji', '2000-04-11', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (47, 'Nari Doale', 21, 'Arendal', '2000-06-04', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (48, 'Cullan Conradsen', 21, 'Xiaohe', '1998-01-05', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (49, 'Stephan Taggett', 19, 'Las Lajas', '1998-11-15', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (50, 'Inglis Vaneev', 20, 'Richmond', '1999-05-03', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (51, 'Tedra Wildin', 20, 'Espinal', '2000-04-25', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (52, 'Tommy Alenin', 21, 'Qarah Ẕīā’ od Dīn', '1999-08-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (53, 'Shelden Culshaw', 19, 'Foúrnoi', '1996-12-07', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (54, 'Smitty Floyde', 21, 'Yag La', '1996-02-27', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (55, 'Avrom Corby', 19, 'Faleula', '1999-08-26', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (56, 'Nissie Twaite', 19, 'Zhongying', '2000-01-21', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (57, 'Devina Groocock', 19, 'Ugba', '1999-03-20', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (58, 'Seumas Beine', 21, 'Roliça', '1999-10-16', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (59, 'Sheridan Tudball', 20, 'Yenakiyeve', '1997-02-09', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (60, 'Artur Runciman', 20, 'Pingtan', '1996-02-23', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (61, 'Trixie Ellerman', 19, 'Vareš', '2000-09-03', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (62, 'Westbrooke Coulthard', 21, 'Masis', '1996-03-08', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (63, 'Sammie Denecamp', 20, 'Ovidiopol’', '1998-09-06', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (64, 'Hurleigh Ivanyushkin', 19, 'Skurup', '1996-02-28', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (65, 'Pat Dolbey', 21, 'Alacaygan', '2000-05-12', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (66, 'Fayth Trehearn', 21, 'Ḩadīdah', '1997-11-05', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (67, 'Ailsun Merrell', 19, 'Būrkah', '1998-12-11', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (68, 'Ingrim Bannister', 21, 'Marumori', '1996-05-23', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (69, 'Darryl Talby', 21, 'Taypano', '2000-08-12', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (70, 'Leonhard Astill', 19, 'Eskilstuna', '1997-12-03', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (71, 'Jesselyn Sapwell', 21, 'Tha Muang', '1998-03-03', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (72, 'Heida Tern', 21, 'Glad', '1996-02-21', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (73, 'Roseline Wheal', 19, 'Guadalupe', '1996-03-08', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (74, 'Dierdre Mariolle', 21, 'Turka', '1998-07-26', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (75, 'Dianemarie Woodcroft', 21, 'Bambous Virieux', '2000-09-04', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (76, 'Merridie Twentyman', 20, 'Dikou', '1998-01-03', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (77, 'Nanny Aloway', 19, 'Fuhai', '1999-03-02', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (78, 'Curtis Scurrer', 21, 'Kotablolong', '1999-09-29', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (79, 'Georgiana Burgot', 20, 'Qijiawan', '1999-04-21', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (80, 'Norrie Waszczykowski', 20, 'Jefferson City', '1996-09-17', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (81, 'Katie Grene', 20, 'Vandœuvre-lès-Nancy', '1996-10-08', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (82, 'Gusta Grinikhinov', 19, 'Rio das Ostras', '2000-04-01', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (83, 'Eddie Coggon', 19, 'Camacupa', '1998-09-21', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (84, 'Alethea Cavendish', 20, 'Matango', '1996-01-26', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (85, 'Forester Pollins', 21, 'Zaliztsi', '1996-12-16', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (86, 'Octavius Monard', 21, 'Ternate', '1998-01-30', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (87, 'Judi Eyckelberg', 19, 'Baranoa', '1996-08-26', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (88, 'Marty Scase', 21, 'Marigot', '1998-12-10', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (89, 'Marsh Marder', 20, 'Lima', '1997-02-25', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (90, 'Datha Whyard', 21, 'São Luiz Gonzaga', '2000-09-27', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (91, 'Kattie Badsworth', 21, 'Lady Frere', '1996-05-21', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (92, 'Elsa Mitrovic', 20, 'Sumber', '1998-12-03', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (93, 'Faustine Sabater', 21, 'Tillabéri', '2000-11-28', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (94, 'Burt McGeagh', 21, 'Clichy', '1999-06-09', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (95, 'Jasmine Cymper', 19, 'La Agustina', '1998-01-17', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (96, 'Halsey Leeves', 20, 'Qa‘ţabah', '1999-03-24', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (97, 'Wilhelmine Easlea', 21, 'Yubileynyy', '1998-06-22', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (98, 'Agustin Amburgy', 20, 'Marale', '1996-08-28', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (99, 'Nola Bilovsky', 20, 'Elista', '1999-12-21', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (100, 'Rakel Cordeix', 19, 'Krong Pi Nang', '1996-08-30', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (101, 'Glenda Spensly', 21, 'Villa Lugano', '2000-10-07', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (102, 'Donna Blaszczak', 20, 'Porto Ferreira', '2000-08-28', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (103, 'Otha Mackett', 21, 'Chagou', '2000-04-22', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (104, 'Osbourn Welberry', 21, 'Shixian', '2000-11-09', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (105, 'Darell Kearton', 21, 'Rāwandūz', '1998-05-19', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (106, 'Annie Attock', 20, 'Hancheng', '1996-05-31', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (107, 'Hildy Dolder', 19, 'Bistrinci', '2000-05-07', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (108, 'Letti Klammt', 20, 'Mae Fa Luang', '1997-07-29', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (109, 'Klarika Scough', 20, 'Golopau', '1998-02-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (110, 'Robinet Hincham', 20, 'Raemude', '1998-06-25', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (111, 'Shauna Comrie', 20, 'Niagara Falls', '1997-12-05', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (112, 'Adam Heatley', 21, 'Árta', '1998-12-15', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (113, 'Octavius Lermit', 20, 'Kupang', '1997-09-10', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (114, 'Gaylord Need', 21, 'Huangcaotuo', '1996-07-05', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (115, 'Cosette Reoch', 20, 'Kamenka', '1997-08-02', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (116, 'Marco Huton', 21, 'Shymkent', '1996-03-24', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (117, 'Hanny Weagener', 20, 'Dengfeng', '1999-01-14', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (118, 'Kylila Henriques', 19, 'Dubiecko', '1997-09-20', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (119, 'Cammi Eplate', 21, 'Maple Plain', '2000-02-12', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (120, 'Ketty Duxbarry', 20, 'Polanica-Zdrój', '1999-07-10', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (121, 'Aurelia Thornbarrow', 21, 'La Huaca', '1999-06-21', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (122, 'Donella Pinckney', 20, 'Langchuan', '1999-07-09', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (123, 'Ernestine Corbridge', 19, 'Kafr Miṣr', '2000-05-07', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (124, 'Ferrell McBayne', 20, 'Bajiazi', '2000-07-06', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (125, 'Brocky Storrah', 21, 'Breves', '1997-05-11', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (126, 'Freddi Conkling', 19, 'Takaoka', '1999-04-16', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (127, 'Fanny Craske', 20, 'Śniadowo', '2000-11-27', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (128, 'Zena Marin', 19, 'Rozhniv', '1997-09-14', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (129, 'Robina Fortesquieu', 19, 'Al Bīrah', '2000-02-11', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (130, 'Karlan Victoria', 19, 'Sebeta', '1999-03-28', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (131, 'Aila Sainer', 19, 'Wan Yai', '1997-03-22', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (132, 'Alister Mosdill', 21, 'Nakhon Luang', '1998-07-11', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (133, 'Goddart Cairns', 21, 'Jiepai', '1996-12-22', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (134, 'Shelbi Reicherz', 20, 'Rejoso', '1996-12-13', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (135, 'Casi Nancarrow', 20, 'Torbeck', '1996-02-17', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (136, 'Whit Tregiddo', 20, 'Daxinshao', '1996-09-02', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (137, 'Francisco Sines', 21, 'Cicapar', '1998-01-07', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (138, 'Orion Adamovich', 20, 'Wushan', '1997-10-04', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (139, 'Zenia Bartels', 21, 'Miguel Calmon', '1999-10-26', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (140, 'Wheeler Mulberry', 20, 'Haljala', '1998-07-17', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (141, 'Rod Ivanishev', 21, 'Mamonit', '1996-12-28', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (142, 'Jammal Lammertz', 20, 'Ciakar', '1997-03-08', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (143, 'Dwain Raulin', 21, 'San Pedro de Lloc', '1998-12-29', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (144, 'Felecia Jewise', 21, 'Dallas', '1999-09-11', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (145, 'Jerrold Bartelot', 19, 'Dongbei', '1997-05-27', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (146, 'Farleigh Learmonth', 19, 'Villasis', '1996-02-14', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (147, 'Clary Mazillius', 19, 'Chơn Thành', '1999-10-07', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (148, 'Zena Scoggan', 21, 'Louisville', '1996-07-08', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (149, 'Judi Dockwra', 19, 'Nueva Ocotepeque', '1996-03-16', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (150, 'Mei Gueste', 21, 'Cibitung', '1997-07-10', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (151, 'Humfrey Stanbra', 19, 'Kuybyshevskiy Zaton', '1997-11-11', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (152, 'Denna Daelman', 20, 'Jeding', '1997-11-05', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (153, 'Tiebout Freda', 21, 'Paris 13', '1997-04-20', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (154, 'Israel Martignon', 21, 'Lebedyn', '1999-04-19', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (155, 'Andres Abba', 20, 'Huangshi', '1997-05-05', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (156, 'Dita Woollends', 21, 'Shuangxikou', '2000-05-05', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (157, 'Jordan Gingel', 20, 'Zeqin', '1997-10-01', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (158, 'Nicolai Mattschas', 20, 'Majiang', '1999-03-18', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (159, 'Elga O''Daly', 21, 'Pelotas', '1999-04-03', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (160, 'Garrott Deverock', 21, 'El Zapote', '1998-04-07', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (161, 'Torin Turk', 21, 'Lukunor', '1996-02-23', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (162, 'Fernande Cavnor', 20, 'Siguinon', '1999-09-05', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (163, 'Ellary Hardman', 21, 'Margorejo', '1998-11-22', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (164, 'Dora Carncross', 20, 'Den Haag', '2000-09-21', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (165, 'Alick Ansell', 20, 'Pitogo', '1996-05-08', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (166, 'Haskel Bodiam', 19, 'Gaosheng', '2000-11-08', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (167, 'Philly Penhalewick', 20, 'Polowat', '1997-10-25', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (168, 'Arabel Brothwell', 19, 'Leteki', '1998-01-30', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (169, 'Henryetta Wymer', 20, 'Grenoble', '1998-09-10', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (170, 'Florri Hasloch', 21, 'Žďár nad Sázavou', '2000-11-12', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (171, 'Angel Wisam', 20, 'Umbulan', '1996-10-02', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (172, 'Lona Chancelier', 19, 'Sūq Şirwāḩ', '1997-01-19', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (173, 'Haslett Kauffman', 21, 'Jomboy', '2000-11-26', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (174, 'Avigdor Lahy', 19, 'Banjar Jambe Baleran', '2000-07-08', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (175, 'Drona Kealy', 20, 'Chvalšiny', '2000-10-27', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (176, 'Bradford Keyho', 21, 'San Quintin', '1996-04-24', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (177, 'Sonnie Ziemecki', 20, 'Särö', '1997-05-24', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (178, 'Olav Nason', 19, 'La Lima', '2000-03-27', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (179, 'Edithe Queripel', 20, 'Wangshi', '2000-04-29', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (180, 'Munroe Hoff', 19, 'Strasbourg', '1999-06-28', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (181, 'Evered Gazey', 21, 'Gostyń', '1997-04-21', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (182, 'Orbadiah Dunan', 19, 'Itabaiana', '2000-08-30', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (183, 'Cornelle Avrahamov', 19, 'Norberg', '1999-10-21', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (184, 'Tull Shelliday', 21, 'Vailoa', '1996-08-07', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (185, 'Caria Roft', 19, 'San José de Miranda', '1999-11-08', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (186, 'Kristian MacFayden', 21, 'Sepolong Timur', '1998-12-29', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (187, 'Talia Yandell', 19, 'Katipunan', '1997-12-17', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (188, 'Florance Penny', 21, 'Quiling', '1997-06-28', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (189, 'Ulrikaumeko Kenningham', 19, 'Bacungan', '2000-07-22', 'Digital Marketing');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (190, 'Earlie Woodfin', 20, 'Fovissste', '1999-07-18', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (191, 'Kelsi Pawnsford', 20, 'Şafwá', '2000-11-21', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (192, 'Shelby Ellwell', 20, 'Apalit', '1997-08-08', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (193, 'Silvan Keppie', 20, 'Haputale', '2000-10-30', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (194, 'Dulce Di Roberto', 20, 'Himanka', '1996-07-07', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (195, 'Jorge Wolsey', 21, 'Meylan', '1996-02-09', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (196, 'Sisile Rignall', 19, 'Gampola', '1996-06-27', 'Teknik Informatika');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (197, 'Viva Enticott', 21, 'Fanzeres', '1999-09-23', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (198, 'Kerstin Eyre', 19, 'Skerries', '2000-10-08', 'Teknik Industri');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (199, 'Nickie Aylmer', 19, 'Kéfalos', '1998-11-18', 'Desain Komunikasi Visual');
insert into tb_mahasiswa (kd_mahasiswa, nama_mahasiswa, kelas, tempat_lahir, tanggal_lahir, jurusan) values (200, 'Kayne Huggill', 20, 'Zuogaiduoma', '1999-08-06', 'Digital Marketing');
